events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;

	# WordPress
	server {
		listen 443 ssl;
		server_name flo-dolc.42.fr;
		root /var/www/html;
		index index.php index.html index.htm;

		location / {
			try_files $uri $uri/ =404;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}

	# Adminer
	server {
		listen 443 ssl;
		server_name adminer.flo-dolc.42.fr;

		location / {
			proxy_pass http://adminer:8080;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}

	# Static Website
	server {
		listen 443 ssl;
		server_name site.flo-dolc.42.fr;

		location / {
			proxy_pass http://website:80;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}
	}

	# Portainer
	server {
		listen 443 ssl;
		server_name portainer.flo-dolc.42.fr;

		location / {
			proxy_pass http://portainer:9000;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}
	}
}
